# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroom',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp', 'sender']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='chatroommembership',
            order_with_respect_to='chat_room',
        ),
    ]
